### ISSUE TITLE
Alert - Chaos Monkey

### ISSUE THREAD

**Issue by aclai4067** [nss-evening-cohort-10/nutshell-jurassic-world#120]
# User Story
As a user, I should be alerted when the Chaos Monkey strikes, including info on what it did, and to whom.

# AC
**WHEN** I am browsing the site
**THEN** I should randomly see the Chaos Monkey strike
**AND** When he strikes, then I should receive a toast that explains what happened and what was affected

# Dev Notes
- Previous developers seem to have code already included that will alert through a toast and print the information on what was changed to the toast.
- Test that the current code is accomplishing the correct notifications.

**Comment by broach44** [comment]
- Schedule a cron job later to ensure the cron is fully functional
- Create a new button for testing the monkey events for the next tickets and turn the cron off until completed

**Comment by broach44** [comment]
No push necessary for this ticket at this time.  Cron is working and pops a toast that alerts the user what happened.
