### ISSUE TITLE
Update ERD

### ISSUE THREAD

**Issue by gseals** [nss-evening-cohort-10/nutshell-jurassic-world#122]
# User Story
As a developer, when I open this, I should see an updated ERD of how our data will interact.

# AC
**WHEN** I open this ticket
**THEN** I should see screenshots of the ERD.

# Dev Notes
- Use Lucid Chart to create an ERD
- Paste them into this ticket for future reference

**Comment by gseals** [comment]
![image](https://user-images.githubusercontent.com/52087296/69482582-decd7c00-0de2-11ea-8a7b-75810f335583.png)

**Comment by maggieisgreene** [comment]
![image](https://user-images.githubusercontent.com/54197223/69483678-e5162500-0def-11ea-8cb6-ea77f9fd482e.png)
