### ISSUE TITLE
mockups

### ISSUE THREAD

**Issue by aclai4067** [nss-evening-cohort-10/nutshell-jurassic-world#123]
# User Story
As a developer, I would like to envision what the end product will look like.
# AC
**WHEN** I open this ticket
**THEN** I should see an updated mockup with the new features
# Dev Notes
- Update previous mockups and include new items necessary
- Create a new mockup for the added components

**Comment by aclai4067** [comment]
Rides:
![image](https://user-images.githubusercontent.com/47763728/69483117-fad41c00-0de8-11ea-81d3-541751da75ad.png)

**Comment by aclai4067** [comment]
Equipment:
![image](https://user-images.githubusercontent.com/47763728/69483381-3ae8ce00-0dec-11ea-8690-6e5d0ae3095c.png)

**Comment by aclai4067** [comment]
Staff: 
![image](https://user-images.githubusercontent.com/47763728/69483666-a5e7d400-0def-11ea-859b-54fb8f5715f1.png)

**Comment by gseals** [comment]
![image](https://user-images.githubusercontent.com/52087296/69483721-74233d00-0df0-11ea-9df7-a33f7fb5a0f8.png)

**Comment by gseals** [comment]
Chaos Log

![image](https://user-images.githubusercontent.com/52087296/69483727-82715900-0df0-11ea-9784-d8a7208ac422.png)

**Comment by aclai4067** [comment]
Dinos: 
![image](https://user-images.githubusercontent.com/47763728/69483730-8ef5b180-0df0-11ea-8952-c4166028f1e8.png)

**Comment by gseals** [comment]
Calendar View Schedule

![image](https://user-images.githubusercontent.com/52087296/69483721-74233d00-0df0-11ea-9df7-a33f7fb5a0f8.png)

**Comment by gseals** [comment]
Calendar View Schedule

![image](https://user-images.githubusercontent.com/52087296/69483771-0fb4ad80-0df1-11ea-8df1-60987ec8b644.png)

**Comment by aclai4067** [comment]
vendors: 
![image](https://user-images.githubusercontent.com/47763728/69483775-23f8aa80-0df1-11ea-8227-bd27866eba44.png)
