### ISSUE TITLE
Refactor Redundant Functions

### ISSUE THREAD

**Issue by aclai4067** [nss-evening-cohort-10/nutshell-jurassic-world#125]
# User Story
As a developer, I should see adjustments to the existing data to set myself up for success, by removing redundancies.

# A/C
**WHEN** I browse through the code
**THEN**  I shouldn't see unnecessary code redundancies.

# Dev Notes
* Combine to just print in a single div called "printComponent"
* Remove all show/hide of the individual divs
* add class `cudButton` to all create/update/delete buttons
* add to authData.js:
```
const checkForUser = () => {
  if (firebase.auth().currentUser) {
    $('.cudButton').removeClass('hide');
    $('#logOutButton').removeClass('hide');
    $('#logButtons').addClass('hide');
  } else {
    $('.cudButton').addClass('hide');
    $('#logOutButton').addClass('hide');
    $('#logButtons').removeClass('hide');
  }
};
```
* call checkForUser() in printToDom()
* remove redundant userModeToggle functions

**Comment by broach44** [comment]
Included in the refactor:
1) Combine to just print in a single div called "printComponent"
2) Remove all show/hide of the individual divs

**Comment by aclai4067** [comment]
Included in refactor:
* add class `cudButton` to all create/update/delete buttons
* add to authData.js
```
const checkForUser = () => {
  if (firebase.auth().currentUser) {
    $('.cudButton').removeClass('hide');
    $('#logOutButton').removeClass('hide');
    $('#logButtons').addClass('hide');
  } else {
    $('.cudButton').addClass('hide');
    $('#logOutButton').addClass('hide');
    $('#logButtons').removeClass('hide');
  }
};
```
* call checkForUser() in printToDom()
* remove redundant userModeToggle functions
