### ISSUE TITLE
Code Test

### ISSUE THREAD

**Issue by broach44** [nss-evening-cohort-10/nutshell-jurassic-world#127]
# User Story
As a developer,  I want to verify the code I have received for a project is bug free before adding new functionality.
# AC
**WHEN** I click on, use, edit, delete, and update
**THEN** I should not receive any errors
**AND** Everything should work as intended
**AND** The changes made should not break other modules
# Dev Notes
- Each developer on the team will be testing a module or two to confirm that the code on that module meets the Acceptable Criteria.
- If a developer identifies a bug, they will then be responsible for opening a new bug ticket and fixing the bug before moving forward with the project.
- Each developer will include their comments within this ticket to confirm this step has been completed
- ensure that deleting every item from a page prints a page without a message without having to hard-refresh the page

**Module Assignments**
- Dinos and Vendors -> Gabe
- Equipment -> Ashley
- Rides -> Maggie
- Staff -> Crystal

**Comment by gseals** [comment]
![image](https://user-images.githubusercontent.com/52087296/69499661-10654680-0eba-11ea-8225-93d514f29933.png)

**Comment by gseals** [comment]
add vendorsUpdate modal back to index.html

**Comment by broach44** [comment]
Creating a new ticket to fix bug on staff page.  Unable to delete all staff members. Leaves the last member and styling is poor the more staff members you fire. Correcting issues in ticket #144.

**Comment by aclai4067** [comment]
addressing equipment bugs in ticket #140
