### ISSUE TITLE
Ride: Read

### ISSUE THREAD

**Issue by kelsey-21** [nss-evening-cohort-10/nutshell-jurassic-world#13]
# USER STORY
As a user, when I arrive at Jurassic World and open the app, I want to be able to see the rides at the park.

# AC
*WHEN* A user opens the app
*THEN* they should see a card for `Rides`
*AND* when they click on this card
*THEN* they should see a full list of all the rides available within the park

# Dev Notes
* This is the `READ` portion for Full crud
* Users should be able to see all items, regardless of login status
* users should be able to click on category card on the dash and then this opens a larger page that reveals the full list of available rides
* this should initially display all the seed data, as well as any additional vendors added to the directory by the `CREATE` function

**Comment by kelsey-21** [comment]
![image](https://user-images.githubusercontent.com/54123694/68821099-f7a39800-0652-11ea-8ffd-d24e81e0decb.png)

**Comment by kelseycreel** [comment]
![image](https://user-images.githubusercontent.com/54123694/68821134-16a22a00-0653-11ea-8c20-3b7eeddcf622.png)

**Comment by kelsey-21** [comment]
![image](https://user-images.githubusercontent.com/54123694/68821173-2d488100-0653-11ea-92eb-c80669ce490e.png)
