### ISSUE TITLE
Scheduling - Assign Staff Vendor

### ISSUE THREAD

**Issue by broach44** [nss-evening-cohort-10/nutshell-jurassic-world#130]
# User Story
As a user, I should be able to assign a staff member to either a dinosaur, a ride, or a vendor.

# AC 
**WHEN** a user navigates to the Schedule page
**THEN** they should be able to assign a staff member to any unassigned vendors
**AND**  after the staff is assigned, the page should reload and the chosen vendor should be removed from the unassigned list.

# Dev Notes
Create a new file in `javascripts/helpers/data` called `vendorStaffData.js`
- Inside this data file, create a new function called `createVendorStaff` which adds a new listing to the vendorStaff data -- use the following function
```
const createNewVendorStaff = (newVendorStaff) => axios.post(`${baseUrl}/vendorStaff.json`, newVendorStaff);
```
Create a new component called `AssignStaffVendor` with two files inside -- `assignStafffVendor.js` and `assignStaffVendor.scss`
- Inside of the javascript file, create a function called `assignStaffVendor` --  create an object called `newVendorStaff`
```
const newVendorStaff = {
staffId: '',
vendorId: '',
shiftId: ''
};
```
- Add jQuery selectors to fill in those blanks with the correct information
- Then, import the `vendorStaffData.js` and call the `createNewVendorStaff` and pass it a parameter of the newVendorStaff object created in the step above
- After the new object is being added to the database successfully, close the modal and reprint the page

**Comment by maggieisgreene** [comment]
<div class="modal fade" id="newVendorStaffModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">New Board</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form>
            <div class="form-group">
              <label for="seating-id">Table Number</label>
              <input type="text" class="form-control" id="seating-id" placeholder="Table Number Here">
            </div>
            <div class="form-group">
              <label for="customer-name">Customer Name</label>
              <input type="text" class="form-control" id="customer-name" placeholder="Enter Customer Name">
            </div>
            <div class="form-group">
              <label for="party-size">Party Size</label>
              <input type="text" class="form-control" id="party-size" placeholder="Enter Party Size">
            </div>
            <div class="form-group">
              <label for="reserve-date">Date</label>
              <input type="date" class="form-control" id="reserve-date" placeholder="Choose Date">
            </div>
            <div class="form-group">
              <label for="reserve-time">Time</label>
              <input type="time" class="form-control" id="reserve-time" placeholder="Choose Time">
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-light" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-light" id="add-new-vendor-staff">Complete Reservation</button>
        </div>
      </div>
    </div>
  </div>
