### ISSUE TITLE
Chaos Monkey: Toast & Interval

### ISSUE THREAD

**Issue by kelsey-21** [nss-evening-cohort-10/nutshell-jurassic-world#18]
# User Story
As a user, I would like to be shown a toast notification whenever the Chaos Monkey strikes within the park so that I am aware of the effects of the monkey

# AC
*WHEN* the chaos monkey strikes at the assigned time interval
*THEN* show the toast notification of the monkey strike

# Dev Notes
* Chaos Monkey should deploy at a set time every day
* Toast should display at time of chaos incident and stay for duration of interval
**STRETCH FEATURES**
* toast remains open unless `x` button is clicked to close it
* toast displays the affected area of the park, `staff`, `equipment`, or `rides`

**Comment by LaCollins** [comment]
Bootstrap Toast
https://getbootstrap.com/docs/4.3/components/toasts/

**Comment by LaCollins** [comment]
How to set a function to go off at certain time of day: https://stackoverflow.com/questions/4455282/call-a-javascript-function-at-a-specific-time-of-day

**Comment by LaCollins** [comment]
https://stackoverflow.com/questions/24741530/in-javascript-how-can-i-have-a-function-run-at-a-specific-time/24741617

**Comment by LaCollins** [comment]
https://www.npmjs.com/package/node-schedule

**Comment by LaCollins** [comment]
https://blog.abelotech.com/posts/nodejs-scheduler-cron-timeout-interval/

**Comment by LaCollins** [comment]
Node Cron!
https://github.com/kelektiv/node-cron

**Comment by LaCollins** [comment]
`npm install cron`
