### ISSUE TITLE
Equipment: Create

### ISSUE THREAD

**Issue by kelsey-21** [nss-evening-cohort-10/nutshell-jurassic-world#20]
# USER STORY
As a Jurassic World Admin, when I arrive at Jurassic World and open the app, I want to be able to see the equipment at the park and I want to be able to add new equipment to my equipment directory

# AC
*WHEN* a user opens the app
*THEN* they should see a card for `equipment `
*AND* when they click on this card
*THEN* they should see a full list of all the equipment available within the park
*AND* they should have the ability to add new equipment to the list

# Dev Notes
* This is the `CREATE` portion for Full crud
* Users should be able to see all equipments, regardless of login status but *only* be able to add new equipment if logged in
* users should be able to click on category card on the dash and then this opens a larger page that reveals the full list of available equipment 
* this should add equipment objects to the directory of equipment

**Comment by djunaim** [comment]
👍
