### ISSUE TITLE
equipment: read

### ISSUE THREAD

**Issue by jacob-bw** [nss-evening-cohort-10/nutshell-jurassic-world#28]
# USER STORY
As a user, when I arrive at Jurassic World and open the app, I want to be able to see the equipment at the park.

# AC
*WHEN* A user opens the app
*THEN* they should see a card for `equipment `
*AND* when they click on this card
*THEN* they should see a full list of all the equipment available within the park

# Dev Notes
* This is the `READ` portion for Full crud
* Users should be able to see all items, regardless of login status
* users should be able to click on category card on the dash and then this opens a larger page that reveals the full list of available equipment 
* this should initially display all the seed data, as well as any additional equipment added to the directory by the `CREATE` function

**Comment by LaCollins** [comment]
![image](https://user-images.githubusercontent.com/51382883/68821096-f5d9d480-0652-11ea-84db-b91e4b6fd155.png)

**Comment by kelsey-21** [comment]
![image](https://user-images.githubusercontent.com/54123694/68821316-9cbe7080-0653-11ea-8ab4-e754b0265172.png)

**Comment by djunaim** [comment]
👍
