### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by djunaim** [nss-evening-cohort-10/nutshell-jurassic-world#30]
# User Story
As a user, I when I load the Jurassic World page, I want to be able to navigate the page.

# AC
**WHEN** The page loads
**THEN** I should see thumbnail pictures of all the available navigation locations
**AND** When I click on an image, it loads the modal.

#Dev Notes
* See below wireframe.
* Use bootstrap grid
* Use `Arial` font unless we find something else.

**Comment by LaCollins** [comment]
![image](https://user-images.githubusercontent.com/51382883/68817378-1f8cfe80-0647-11ea-8fec-51595cf2d5f1.png)

**Comment by LaCollins** [comment]
![image](https://user-images.githubusercontent.com/51382883/68817397-303d7480-0647-11ea-9c58-13f203646615.png)

**Comment by kelsey-21** [comment]
![image](https://user-images.githubusercontent.com/54123694/68821247-6f71c280-0653-11ea-8625-ae2f3d0b795e.png)
