### ISSUE TITLE
vendors: delete

### ISSUE THREAD

**Issue by jacob-bw** [nss-evening-cohort-10/nutshell-jurassic-world#32]
# USER STORY
As a Jurassic World Admin, when I arrive at Jurassic World and open the app, I want to be able to see the vendors at the park and I want to be able to delete vendors from my vendor directory

# AC
*WHEN* a user opens the app
*THEN* they should see a card for `Vendors`
*AND* when they click on this card
*THEN* they should see a full list of all the vendors available within the park
*AND* they should have the ability to delete vendors from the list

# Dev Notes
* This is the `DELETE` portion for Full crud
* users should be able to click on category card on the dash and then this opens a larger page that reveals the full list of available vendors
* Users should be able to see all vendors, regardless of login status but *only* be able to delete vendors if logged in
* this should delete vendor objects from the directory of vendors regardless of whether they were seed data created in #31 or added as built in #35

**Comment by LaCollins** [comment]
![image](https://user-images.githubusercontent.com/51382883/68821392-d55e4a00-0653-11ea-807d-02d7f2dd8eaf.png)

**Comment by LaCollins** [comment]
![image](https://user-images.githubusercontent.com/51382883/68821544-4271df80-0654-11ea-8af7-25843ea3cd3e.png)
