### ISSUE TITLE
vendors: update

### ISSUE THREAD

**Issue by jacob-bw** [nss-evening-cohort-10/nutshell-jurassic-world#33]
# USER STORY
As a Jurassic World Admin, when I arrive at Jurassic World and open the app, I want to be able to see the vendors at the park and I want to be able to update the vendors within my vendor directory

# AC
*WHEN* a user opens the app
*THEN* they should see a card for `Vendors`
*AND* when they click on this card
*THEN* they should see a full list of all the vendors available within the park
*AND IF* they are logged in, they should have the ability to update vendors in the list

# Dev Notes
* This is the `UPDATE` portion for Full crud
* Users should be able to see all vendors, regardless of login status but *only* be able to update vendors if logged in
* users should be able to click on category card on the dash and then this opens a larger page that reveals the full list of available vendors
* this should update vendor objects

**Comment by LaCollins** [comment]
![image](https://user-images.githubusercontent.com/51382883/68821400-de4f1b80-0653-11ea-9e5b-5271b8aa5a52.png)

**Comment by LaCollins** [comment]
![image](https://user-images.githubusercontent.com/51382883/68821538-3b4ad180-0654-11ea-9361-6961d37c2441.png)
