### ISSUE TITLE
vendors: read

### ISSUE THREAD

**Issue by jacob-bw** [nss-evening-cohort-10/nutshell-jurassic-world#34]
# USER STORY
As a user, when I arrive at Jurassic World and open the app, I want to be able to see the vendors at the park that I can buy various goods from.

# AC
*WHEN* A user opens the app
*THEN* they should see a card for `Vendors`
*AND* when they click on this card
*THEN* they should see a full list of all the vendors available within the park

# Dev Notes
* This is the `READ` portion for Full crud
* Users should be able to see all items, regardless of login status
* users should be able to click on category card on the dash and then this opens a larger page that reveals the full list of available vendors
* this should initially display all the seed data, as well as any additional vendors added to the directory by the `CREATE` function

**Comment by LaCollins** [comment]
![image](https://user-images.githubusercontent.com/51382883/68821412-e5762980-0653-11ea-99d6-00acc6783342.png)

**Comment by LaCollins** [comment]
![image](https://user-images.githubusercontent.com/51382883/68821523-31c16980-0654-11ea-9377-af35b6f5fffe.png)
