### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by kelsey-21** [nss-evening-cohort-10/nutshell-jurassic-world#9]
# User Story
As a developer, I want to start my project correctly, and know that I have all the tools necessary to successfully build and display my page

# AC
WHEN I open this project on my computer
THEN I should see my directory with webpack and eslint installed and configured
AND jquery and bootsrap should be configured

# Dev Notes
- installs can be found here: https://github.com/nss-nightclass-projects/Night-Class-Resources/blob/master/book-2-patterns-and-tools/chapters/webpack-installs.md

- webpack configuration requirements can be found here: https://github.com/nss-nightclass-projects/Night-Class-Resources/blob/master/book-2-patterns-and-tools/chapters/webpack-configure.md

- ES Lint configuration requirements can be found here: https://github.com/nss-nightclass-projects/Night-Class-Resources/blob/master/book-2-patterns-and-tools/chapters/webpack-eslint.md

- front end dependencies found here: https://github.com/nss-nightclass-projects/Night-Class-Resources/blob/master/book-2-patterns-and-tools/chapters/webpack-frontend-dependencies.md

- running webpack guide can be found here: https://github.com/nss-nightclass-projects/Night-Class-Resources/blob/master/book-2-patterns-and-tools/chapters/webpack-run.md

- root should contain `src` subfolder
- `src` should contain two subfolders: `javascripts` and `styles`
- `javascripts` should contain main.js
- `styles` should contain main.scss
- `src` should contain index.html

**Comment by LaCollins** [comment]
installing font awesome
bash: npm install --save @fortawesome/fontawesome-free
main.js: import '@fortawesome/fontawesome-free/js/all';
